server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        # Si le fichier/dossier n'existe pas, on renvoie index.html pour le routeur JS
        try_files $uri $uri/ /index.html;
    }
}