nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['X-AUTH-TOKEN', 'Content-Type', 'Authorization', 'Accept']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/api/': ~      # Active CORS sur toutes les routes commençant par /api/
        '^/': ~         # Ou sur toutes les routes du backend
